"""MEMBRA CompanyOS — Data Source Registry (22 Approved Sources).

Each data source includes:
- source_id, name, type, base_url
- auth_required, rate_limit, reliability_score
- freshness_seconds, allowed_departments, cache_policy
"""
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class DataSourceConfig(BaseModel):
    source_id: str
    name: str
    type: str  # rpc, api, subgraph, feed, node
    base_url: Optional[str] = None
    auth_required: bool
    rate_limit: str  # e.g. "100/minute"
    reliability_score: float = Field(ge=0.0, le=1.0)
    freshness_seconds: int
    allowed_departments: List[str]
    cache_policy: Dict[str, Any]
    description: str
    chain: Optional[str] = None
    fallback_sources: List[str] = Field(default_factory=list)
    compliance_notes: str = ""


DATA_SOURCES: List[DataSourceConfig] = [
    DataSourceConfig(
        source_id="solana_rpc",
        name="Solana RPC",
        type="rpc",
        base_url="https://api.mainnet-beta.solana.com",
        auth_required=False,
        rate_limit="100/minute",
        reliability_score=0.92,
        freshness_seconds=2,
        allowed_departments=[
            "dept-strategy", "dept-product", "dept-engineering",
            "dept-operations", "dept-sales", "dept-finance",
            "dept-legal", "dept-governance", "dept-proof",
            "dept-marketing",
        ],
        cache_policy={"ttl_seconds": 5, "strategy": "lru", "max_size": 10000},
        description="Primary Solana JSON-RPC endpoint for account data, transactions, and slot info.",
        chain="solana",
        fallback_sources=["helius_rpc", "quicknode_solana"],
        compliance_notes="Public endpoint; no auth material stored.",
    ),
    DataSourceConfig(
        source_id="ethereum_rpc",
        name="Ethereum RPC",
        type="rpc",
        base_url="https://eth.llamarpc.com",
        auth_required=False,
        rate_limit="100/minute",
        reliability_score=0.94,
        freshness_seconds=12,
        allowed_departments=[
            "dept-strategy", "dept-product", "dept-engineering",
            "dept-operations", "dept-sales", "dept-finance",
            "dept-legal", "dept-governance", "dept-proof",
            "dept-marketing",
        ],
        cache_policy={"ttl_seconds": 12, "strategy": "lru", "max_size": 10000},
        description="Ethereum JSON-RPC for blocks, transactions, receipts, and contract state.",
        chain="ethereum",
        fallback_sources=["alchemy_ethereum", "infura_ethereum"],
        compliance_notes="Public endpoint; rate limit monitored.",
    ),
    DataSourceConfig(
        source_id="bitcoin_node",
        name="Bitcoin Node/API",
        type="api",
        base_url="https://mempool.space/api",
        auth_required=False,
        rate_limit="50/minute",
        reliability_score=0.90,
        freshness_seconds=60,
        allowed_departments=[
            "dept-strategy", "dept-engineering", "dept-operations",
            "dept-finance", "dept-governance", "dept-proof",
        ],
        cache_policy={"ttl_seconds": 60, "strategy": "lru", "max_size": 5000},
        description="Bitcoin mempool and block data via mempool.space API.",
        chain="bitcoin",
        fallback_sources=["blockstream_api"],
        compliance_notes="Public blockchain data only.",
    ),
    DataSourceConfig(
        source_id="dex_screener",
        name="DEX Screener",
        type="api",
        base_url="https://api.dexscreener.com",
        auth_required=False,
        rate_limit="300/minute",
        reliability_score=0.88,
        freshness_seconds=30,
        allowed_departments=[
            "dept-strategy", "dept-product", "dept-finance",
            "dept-sales", "dept-marketing",
        ],
        cache_policy={"ttl_seconds": 30, "strategy": "lru", "max_size": 5000},
        description="Real-time DEX pair data, price, volume, and liquidity across chains.",
        chain="multi",
        fallback_sources=["birdeye"],
        compliance_notes="Third-party aggregator; verify against primary sources.",
    ),
    DataSourceConfig(
        source_id="birdeye",
        name="Birdeye",
        type="api",
        base_url="https://public-api.birdeye.so",
        auth_required=True,
        rate_limit="150/minute",
        reliability_score=0.89,
        freshness_seconds=15,
        allowed_departments=[
            "dept-strategy", "dept-finance", "dept-engineering",
            "dept-operations", "dept-sales",
        ],
        cache_policy={"ttl_seconds": 15, "strategy": "lru", "max_size": 8000},
        description="Solana token prices, OHLCV, and wallet analytics.",
        chain="solana",
        fallback_sources=["dex_screener", "jupiter_quote"],
        compliance_notes="API key required; key stored in secure vault only.",
    ),
    DataSourceConfig(
        source_id="jupiter_quote",
        name="Jupiter Quote API",
        type="api",
        base_url="https://quote-api.jup.ag",
        auth_required=False,
        rate_limit="600/minute",
        reliability_score=0.95,
        freshness_seconds=5,
        allowed_departments=[
            "dept-strategy", "dept-finance", "dept-engineering",
            "dept-operations", "dept-sales",
        ],
        cache_policy={"ttl_seconds": 5, "strategy": "lru", "max_size": 10000},
        description="Best swap routes and quotes across Solana DEXs via Jupiter aggregator.",
        chain="solana",
        fallback_sources=["raydium_pools", "orca_pools"],
        compliance_notes="Quote-only API; no execution.",
    ),
    DataSourceConfig(
        source_id="orca_pools",
        name="Orca Pools",
        type="api",
        base_url="https://api.orca.so",
        auth_required=False,
        rate_limit="200/minute",
        reliability_score=0.91,
        freshness_seconds=10,
        allowed_departments=[
            "dept-finance", "dept-engineering", "dept-strategy",
            "dept-operations",
        ],
        cache_policy={"ttl_seconds": 10, "strategy": "lru", "max_size": 6000},
        description="Orca Whirlpool liquidity pool data, fees, and APR.",
        chain="solana",
        fallback_sources=["raydium_pools", "jupiter_quote"],
        compliance_notes="Liquidity data only; no user positions accessed.",
    ),
    DataSourceConfig(
        source_id="raydium_pools",
        name="Raydium Pools",
        type="api",
        base_url="https://api.raydium.io",
        auth_required=False,
        rate_limit="200/minute",
        reliability_score=0.90,
        freshness_seconds=10,
        allowed_departments=[
            "dept-finance", "dept-engineering", "dept-strategy",
            "dept-operations",
        ],
        cache_policy={"ttl_seconds": 10, "strategy": "lru", "max_size": 6000},
        description="Raydium AMM pool data, farming rewards, and liquidity metrics.",
        chain="solana",
        fallback_sources=["orca_pools", "jupiter_quote"],
        compliance_notes="Public pool data only.",
    ),
    DataSourceConfig(
        source_id="uniswap_subgraphs",
        name="Uniswap Subgraphs",
        type="subgraph",
        base_url="https://api.thegraph.com/subgraphs/name/uniswap",
        auth_required=False,
        rate_limit="100/minute",
        reliability_score=0.87,
        freshness_seconds=60,
        allowed_departments=[
            "dept-strategy", "dept-finance", "dept-engineering",
            "dept-operations",
        ],
        cache_policy={"ttl_seconds": 60, "strategy": "lru", "max_size": 4000},
        description="Uniswap V2/V3 historical and real-time swap, liquidity, and fee data.",
        chain="ethereum",
        fallback_sources=["dex_screener"],
        compliance_notes="Indexed data may lag; verify critical values on-chain.",
    ),
    DataSourceConfig(
        source_id="chainlink_price_feeds",
        name="Chainlink Price Feeds",
        type="api",
        base_url="https://cl-api.url",
        auth_required=False,
        rate_limit="1000/minute",
        reliability_score=0.97,
        freshness_seconds=60,
        allowed_departments=[
            "dept-strategy", "dept-finance", "dept-engineering",
            "dept-operations", "dept-governance", "dept-proof",
        ],
        cache_policy={"ttl_seconds": 60, "strategy": "lru", "max_size": 3000},
        description="Decentralized oracle price feeds for major crypto assets.",
        chain="multi",
        fallback_sources=["coingecko", "defillama"],
        compliance_notes="Oracle data; deviation threshold monitored.",
    ),
    DataSourceConfig(
        source_id="coingecko",
        name="CoinGecko",
        type="api",
        base_url="https://api.coingecko.com/api/v3",
        auth_required=False,
        rate_limit="30/minute",
        reliability_score=0.85,
        freshness_seconds=60,
        allowed_departments=[
            "dept-strategy", "dept-product", "dept-finance",
            "dept-sales", "dept-marketing", "dept-legal",
            "dept-governance",
        ],
        cache_policy={"ttl_seconds": 120, "strategy": "lru", "max_size": 5000},
        description="Cryptocurrency prices, market cap, volume, and exchange data.",
        chain="multi",
        fallback_sources=["defillama", "coinmarketcap"],
        compliance_notes="Free tier limits apply; cached aggressively.",
    ),
    DataSourceConfig(
        source_id="defillama",
        name="DefiLlama",
        type="api",
        base_url="https://api.llama.fi",
        auth_required=False,
        rate_limit="100/minute",
        reliability_score=0.90,
        freshness_seconds=300,
        allowed_departments=[
            "dept-strategy", "dept-finance", "dept-engineering",
            "dept-sales", "dept-marketing", "dept-legal",
            "dept-governance",
        ],
        cache_policy={"ttl_seconds": 300, "strategy": "lru", "max_size": 4000},
        description="DeFi TVL, yields, protocol revenue, and chain analytics.",
        chain="multi",
        fallback_sources=["coingecko"],
        compliance_notes="Public aggregator data; good for relative comparisons.",
    ),
    DataSourceConfig(
        source_id="mempool_space",
        name="Mempool.space",
        type="api",
        base_url="https://mempool.space/api",
        auth_required=False,
        rate_limit="50/minute",
        reliability_score=0.91,
        freshness_seconds=30,
        allowed_departments=[
            "dept-engineering", "dept-operations", "dept-finance",
            "dept-governance", "dept-proof",
        ],
        cache_policy={"ttl_seconds": 30, "strategy": "lru", "max_size": 3000},
        description="Bitcoin mempool, fees, and block explorer data.",
        chain="bitcoin",
        fallback_sources=["blockstream_api"],
        compliance_notes="Public mempool data.",
    ),
    DataSourceConfig(
        source_id="whale_alert_feeds",
        name="Whale Alert Feeds",
        type="feed",
        base_url="https://api.whale-alert.io",
        auth_required=True,
        rate_limit="60/minute",
        reliability_score=0.82,
        freshness_seconds=30,
        allowed_departments=[
            "dept-strategy", "dept-finance", "dept-operations",
            "dept-sales", "dept-governance",
        ],
        cache_policy={"ttl_seconds": 60, "strategy": "lru", "max_size": 2000},
        description="Large transaction alerts across major chains.",
        chain="multi",
        fallback_sources=["mempool_space"],
        compliance_notes="API key required; aggregation not guaranteed.",
    ),
    DataSourceConfig(
        source_id="github_activity",
        name="GitHub Repo Activity",
        type="api",
        base_url="https://api.github.com",
        auth_required=True,
        rate_limit="5000/hour",
        reliability_score=0.95,
        freshness_seconds=3600,
        allowed_departments=[
            "dept-product", "dept-engineering", "dept-sales",
            "dept-marketing", "dept-hr",
        ],
        cache_policy={"ttl_seconds": 3600, "strategy": "lru", "max_size": 2000},
        description="Repository commits, issues, releases, and contributor activity.",
        chain=None,
        fallback_sources=[],
        compliance_notes="Token stored in vault; only public repos monitored.",
    ),
    DataSourceConfig(
        source_id="x_social_sentiment",
        name="X/Social Sentiment Source",
        type="feed",
        base_url="https://api.twitter.com/2",
        auth_required=True,
        rate_limit="300/15min",
        reliability_score=0.75,
        freshness_seconds=300,
        allowed_departments=[
            "dept-product", "dept-sales", "dept-marketing",
            "dept-strategy", "dept-concierge",
        ],
        cache_policy={"ttl_seconds": 300, "strategy": "lru", "max_size": 3000},
        description="Social media sentiment, mentions, and trend analysis (placeholder integration).",
        chain=None,
        fallback_sources=["lunarcrush", "sentiment_io"],
        compliance_notes="Sentiment data for research only; not investment advice.",
    ),
    DataSourceConfig(
        source_id="internal_ledger",
        name="Internal MEMBRA Ledger",
        type="api",
        base_url="internal",
        auth_required=True,
        rate_limit="10000/minute",
        reliability_score=0.99,
        freshness_seconds=1,
        allowed_departments=[
            "dept-strategy", "dept-operations", "dept-finance",
            "dept-governance", "dept-proof", "dept-hr",
            "dept-concierge", "dept-legal", "dept-sales",
        ],
        cache_policy={"ttl_seconds": 1, "strategy": "no_cache"},
        description="MEMBRA's internal transaction ledger, accounting, and audit records.",
        chain=None,
        fallback_sources=[],
        compliance_notes="Highest reliability; direct database connection.",
    ),
    DataSourceConfig(
        source_id="treasury_balances",
        name="Treasury Balances",
        type="api",
        base_url="internal",
        auth_required=True,
        rate_limit="1000/minute",
        reliability_score=0.99,
        freshness_seconds=5,
        allowed_departments=[
            "dept-strategy", "dept-finance", "dept-operations",
            "dept-governance", "dept-proof", "dept-concierge",
        ],
        cache_policy={"ttl_seconds": 5, "strategy": "lru", "max_size": 500},
        description="Real-time treasury wallet balances across all chains and tokens.",
        chain="multi",
        fallback_sources=["solana_rpc", "ethereum_rpc"],
        compliance_notes="Internal read-only; no signing capability.",
    ),
    DataSourceConfig(
        source_id="proofbook_events",
        name="ProofBook Events",
        type="api",
        base_url="internal",
        auth_required=True,
        rate_limit="10000/minute",
        reliability_score=0.99,
        freshness_seconds=1,
        allowed_departments=[
            "dept-operations", "dept-governance", "dept-proof",
            "dept-legal", "dept-hr", "dept-finance",
        ],
        cache_policy={"ttl_seconds": 1, "strategy": "no_cache"},
        description="Immutable ProofBook event stream for audit, compliance, and verification.",
        chain=None,
        fallback_sources=[],
        compliance_notes="Chain-of-custody verified; no caching for integrity reads.",
    ),
    DataSourceConfig(
        source_id="governance_proposals",
        name="Governance Proposals",
        type="api",
        base_url="internal",
        auth_required=True,
        rate_limit="1000/minute",
        reliability_score=0.98,
        freshness_seconds=10,
        allowed_departments=[
            "dept-strategy", "dept-product", "dept-sales",
            "dept-governance", "dept-proof", "dept-legal",
            "dept-marketing", "dept-hr",
        ],
        cache_policy={"ttl_seconds": 10, "strategy": "lru", "max_size": 1000},
        description="Active and historical governance proposals, votes, and outcomes.",
        chain=None,
        fallback_sources=[],
        compliance_notes="Internal governance data; quorum and outcome verified.",
    ),
    DataSourceConfig(
        source_id="risk_blacklist",
        name="Risk Blacklist",
        type="api",
        base_url="internal",
        auth_required=True,
        rate_limit="5000/minute",
        reliability_score=0.97,
        freshness_seconds=60,
        allowed_departments=[
            "dept-legal", "dept-governance", "dept-proof",
            "dept-operations", "dept-finance", "dept-strategy",
        ],
        cache_policy={"ttl_seconds": 60, "strategy": "lru", "max_size": 2000},
        description="Blacklisted contracts, tokens, addresses, and jurisdictions.",
        chain="multi",
        fallback_sources=["sanctions_compliance_provider"],
        compliance_notes="Updated within 1h of new sanctions or threat intel.",
    ),
    DataSourceConfig(
        source_id="sanctions_compliance_provider",
        name="Sanctions/Compliance Provider",
        type="api",
        base_url="https://api.chainalysis.com",
        auth_required=True,
        rate_limit="100/minute",
        reliability_score=0.93,
        freshness_seconds=3600,
        allowed_departments=[
            "dept-legal", "dept-governance", "dept-proof",
            "dept-operations", "dept-finance",
        ],
        cache_policy={"ttl_seconds": 3600, "strategy": "lru", "max_size": 5000},
        description="Sanctions screening, compliance risk scores, and entity verification (placeholder integration).",
        chain="multi",
        fallback_sources=["risk_blacklist"],
        compliance_notes="Sensitive API; key in vault only. Results not cached long-term.",
    ),
]


DATASOURCE_MAP: Dict[str, DataSourceConfig] = {d.source_id: d for d in DATA_SOURCES}


def get_datasource(source_id: str) -> DataSourceConfig:
    if source_id not in DATASOURCE_MAP:
        raise ValueError(f"Data source {source_id} not found")
    return DATASOURCE_MAP[source_id]


def list_datasources() -> List[DataSourceConfig]:
    return DATA_SOURCES


def datasources_for_department(department_id: str) -> List[DataSourceConfig]:
    return [d for d in DATA_SOURCES if department_id in d.allowed_departments]
